#!/usr/bin/env python3

"""
Generate Open Graph images and social metadata for vRSS blog posts.

Input:
    blog/*.html

Output:
    assets/og/<post>.png
    Updated blog/*.html with OG + Twitter metadata
"""

from html import unescape
from html.parser import HTMLParser
from pathlib import Path
from datetime import datetime, timezone
import html
import os
import re

from PIL import Image, ImageDraw, ImageFont


SITE_URL = os.getenv(
    "VRSS_SITE_URL",
    "https://blog.vorcinex.yocrrz.is-a.dev",
).rstrip("/")


BLOG_DIR = Path("blog")
OG_DIR = Path("assets/og")


WIDTH = 1200
HEIGHT = 630


# vRSS palette
PAPER = "#f7f3e8"
PAPER_DEEP = "#eee8d8"
SURFACE = "#fbf9f3"

INK = "#252321"
INK_SOFT = "#4f4a43"
MUTED = "#817b70"
FAINT = "#aaa397"

BORDER = "#ded8c9"
ACCENT = "#c45a3d"


class MetadataParser(HTMLParser):
    """
    Extract the metadata already generated by the vRSS server.
    """

    def __init__(self):
        super().__init__()

        self.title = ""
        self.description = ""
        self.timestamp = ""
        self.author = ""

        self._in_author = False
        self._author_text = []

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attrs = dict(attrs)

        if tag == "meta":
            name = attrs.get("name", "").lower()
            content = attrs.get("content", "")

            if name == "blog-title":
                self.title = unescape(content)

            elif name == "description":
                self.description = unescape(content)

            elif name == "blog-timestamp":
                self.timestamp = unescape(content)

        elif tag == "div":
            classes = attrs.get("class", "").split()

            if "author" in classes:
                self._in_author = True

    def handle_endtag(self, tag):
        if tag.lower() == "div" and self._in_author:
            self._in_author = False

            text = " ".join(self._author_text)
            text = re.sub(r"\s+", " ", text).strip()

            match = re.search(
                r"Published\s+by\s+(.+)$",
                text,
                re.IGNORECASE,
            )

            if match:
                self.author = match.group(1).strip()

            self._author_text = []

    def handle_data(self, data):
        if self._in_author:
            self._author_text.append(data)


class BodyTextParser(HTMLParser):
    """
    Extract readable text from the article body.
    """

    def __init__(self):
        super().__init__()

        self.text = []

        self._skip = 0

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()

        if tag in {
            "script",
            "style",
            "svg",
            "noscript",
            "iframe",
        }:
            self._skip += 1

    def handle_endtag(self, tag):
        tag = tag.lower()

        if tag in {
            "script",
            "style",
            "svg",
            "noscript",
            "iframe",
        }:
            self._skip = max(0, self._skip - 1)

    def handle_data(self, data):
        if self._skip:
            return

        data = data.strip()

        if data:
            self.text.append(data)


def clean_text(value):
    """
    Convert HTML-ish text into readable plain text.
    """

    value = unescape(value)

    value = re.sub(
        r"<[^>]+>",
        " ",
        value,
    )

    value = re.sub(
        r"\s+",
        " ",
        value,
    )

    return value.strip()


def truncate_text(value, length=160):
    value = clean_text(value)

    if len(value) <= length:
        return value

    return value[: length - 1].rstrip() + "…"


def parse_timestamp(timestamp):
    """
    Convert an ISO timestamp into UTC.
    """

    if not timestamp:
        return None

    try:
        dt = datetime.fromisoformat(timestamp)

    except ValueError:
        return None

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)

    return dt.astimezone(timezone.utc)


def format_date(timestamp):
    dt = parse_timestamp(timestamp)

    if not dt:
        return ""

    return dt.strftime("%d %b %Y")


def format_url(path):
    """
    Convert blog/<file>.html into the public URL.
    """

    relative = path.as_posix().lstrip("/")

    return f"{SITE_URL}/{relative}"


def get_font(paths, size):
    """
    Load the first available font from the supplied paths.
    """

    for path in paths:
        path = Path(path)

        if path.exists():
            return ImageFont.truetype(
                str(path),
                size,
            )

    return ImageFont.load_default()


def get_fonts():
    """
    Use fonts available on GitHub Actions runners.
    """

    serif_regular = get_font(
        [
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSerif-Regular.ttf",
        ],
        64,
    )

    serif_bold = get_font(
        [
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationSerif-Bold.ttf",
        ],
        64,
    )

    mono = get_font(
        [
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf",
        ],
        22,
    )

    mono_small = get_font(
        [
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
            "/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf",
        ],
        17,
    )

    return {
        "title": serif_bold,
        "mono": mono,
        "mono_small": mono_small,
    }


def wrap_text(draw, text, font, max_width):
    """
    Word-wrap text so it fits within max_width.
    """

    words = text.split()

    lines = []
    current = ""

    for word in words:
        candidate = (
            word
            if not current
            else f"{current} {word}"
        )

        bbox = draw.textbbox(
            (0, 0),
            candidate,
            font=font,
        )

        width = bbox[2] - bbox[0]

        if width <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)

            current = word

    if current:
        lines.append(current)

    return lines


def draw_title(draw, title, font):
    """
    Draw a large editorial title.
    """

    max_width = 1020

    lines = wrap_text(
        draw,
        title,
        font,
        max_width,
    )

    # Keep the image from becoming overcrowded.
    if len(lines) > 3:
        lines = lines[:3]

        last = lines[-1]

        if len(last) > 3:
            lines[-1] = last.rstrip(" .,-") + "…"

    x = 90
    y = 190

    line_spacing = 8

    for line in lines:
        draw.text(
            (x, y),
            line,
            font=font,
            fill=INK,
        )

        bbox = draw.textbbox(
            (x, y),
            line,
            font=font,
        )

        height = bbox[3] - bbox[1]

        y += height + line_spacing

    return y


def generate_image(
    title,
    description,
    timestamp,
    author,
    output,
):
    """
    Generate the 1200x630 OG image.
    """

    image = Image.new(
        "RGB",
        (WIDTH, HEIGHT),
        PAPER,
    )

    draw = ImageDraw.Draw(image)

    fonts = get_fonts()

    # Outer border
    draw.rectangle(
        (
            24,
            24,
            WIDTH - 25,
            HEIGHT - 25,
        ),
        outline=BORDER,
        width=2,
    )

    # Accent mark
    draw.ellipse(
        (
            82,
            76,
            96,
            90,
        ),
        fill=ACCENT,
    )

    # Brand
    draw.text(
        (115, 70),
        "VORCINEX_STUDIO",
        font=fonts["mono"],
        fill=INK,
    )

    # vRSS label
    draw.text(
        (90, 130),
        "DAILY BLOG",
        font=fonts["mono_small"],
        fill=MUTED,
    )

    # Title
    draw_title(
        draw,
        title,
        fonts["title"],
    )

    # Metadata
    date = format_date(timestamp)

    metadata = []

    if author:
        metadata.append(author)

    if date:
        metadata.append(date)

    metadata_text = " · ".join(metadata)

    if metadata_text:
        draw.text(
            (90, 490),
            metadata_text,
            font=fonts["mono_small"],
            fill=MUTED,
        )

    # Bottom domain
    draw.text(
        (90, 555),
        "blog.vorcinex.yocrrz.is-a.dev",
        font=fonts["mono_small"],
        fill=FAINT,
    )

    # Small accent line
    draw.line(
        (
            WIDTH - 260,
            560,
            WIDTH - 90,
            560,
        ),
        fill=ACCENT,
        width=2,
    )

    output.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    image.save(
        output,
        format="PNG",
        optimize=True,
    )


GENERATED_META_NAMES = {
    "og:title",
    "og:description",
    "og:type",
    "og:url",
    "og:image",
    "og:image:width",
    "og:image:height",
    "og:site_name",
    "article:published_time",
    "twitter:card",
    "twitter:title",
    "twitter:description",
    "twitter:image",
}


def remove_generated_tags(content):
    """
    Remove previously generated OG/Twitter tags.

    This makes the generator idempotent.
    """

    pattern = re.compile(
        r"\s*<meta\s+"
        r"(?:property|name)\s*=\s*"
        r"""(["'])(?:og:title|og:description|og:type|og:url|og:image|"""
        r"""og:image:width|og:image:height|og:site_name|"""
        r"""article:published_time|twitter:card|twitter:title|"""
        r"""twitter:description|twitter:image)\1"""
        r"""[^>]*>\s*""",
        re.IGNORECASE,
    )

    return pattern.sub(
        "\n",
        content,
    )


def inject_metadata(
    content,
    title,
    description,
    timestamp,
    post_url,
    image_url,
):
    """
    Inject OG and Twitter metadata into <head>.
    """

    content = remove_generated_tags(content)

    escaped_title = html.escape(
        title,
        quote=True,
    )

    escaped_description = html.escape(
        description,
        quote=True,
    )

    escaped_timestamp = html.escape(
        timestamp,
        quote=True,
    )

    escaped_url = html.escape(
        post_url,
        quote=True,
    )

    escaped_image = html.escape(
        image_url,
        quote=True,
    )

    tags = f"""
    <meta property="og:title" content="{escaped_title}">
    <meta property="og:description" content="{escaped_description}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{escaped_url}">
    <meta property="og:image" content="{escaped_image}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:site_name" content="VORCINEX_STUDIO vRSS">
    <meta property="article:published_time" content="{escaped_timestamp}">

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="{escaped_title}">
    <meta name="twitter:description" content="{escaped_description}">
    <meta name="twitter:image" content="{escaped_image}">
"""

    head_match = re.search(
        r"</head>",
        content,
        re.IGNORECASE,
    )

    if not head_match:
        raise RuntimeError(
            "Could not find </head> in blog HTML."
        )

    position = head_match.start()

    return (
        content[:position]
        + tags
        + "\n"
        + content[position:]
    )


def process_blog(path):
    """
    Process one blog post.
    """

    original = path.read_text(
        encoding="utf-8",
    )

    parser = MetadataParser()

    parser.feed(original)

    title = clean_text(
        parser.title
    )

    description = clean_text(
        parser.description
    )

    timestamp = parser.timestamp.strip()

    author = clean_text(
        parser.author
    )

    # If the server description is missing or unusable,
    # generate one from the article body.
    if not description:
        body_parser = BodyTextParser()
        body_parser.feed(original)

        description = truncate_text(
            " ".join(body_parser.text),
            160,
        )

    else:
        description = truncate_text(
            description,
            160,
        )

    if not title:
        print(
            f"Skipping {path}: missing blog-title."
        )
        return False

    if not timestamp:
        print(
            f"Skipping {path}: missing blog-timestamp."
        )
        return False

    post_url = format_url(path)

    image_name = f"{path.stem}.png"

    image_path = OG_DIR / image_name

    image_url = (
        f"{SITE_URL}/assets/og/{image_name}"
    )

    generate_image(
        title=title,
        description=description,
        timestamp=timestamp,
        author=author,
        output=image_path,
    )

    updated = inject_metadata(
        content=original,
        title=title,
        description=description,
        timestamp=timestamp,
        post_url=post_url,
        image_url=image_url,
    )

    if updated != original:
        path.write_text(
            updated,
            encoding="utf-8",
        )

        changed = "updated"

    else:
        changed = "unchanged"

    print(
        f"{changed}: {path} → {image_path}"
    )

    return True


def main():
    BLOG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    OG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    posts = sorted(
        BLOG_DIR.glob("*.html")
    )

    if not posts:
        print(
            "No blog posts found."
        )
        return

    processed = 0

    for path in posts:
        if process_blog(path):
            processed += 1

    print()
    print(
        f"Processed {processed}/{len(posts)} blog posts."
    )


if __name__ == "__main__":
    main()
